# Generated by Django 6.1 on 2026-08-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anilist_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
